server {
    # Listen di port 443 untuk semua IP yang masuk ke container
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    # Menerima request dari IP mana pun (Manager/Worker/Localhost)
    # Simbol "_" bertindak sebagai wildcard
    server_name _;

    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;

    # =========================
    # Global Proxy Settings
    # =========================
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Cookie $http_cookie;
    proxy_pass_header Set-Cookie;
    proxy_buffering off;

    # =========================
    # Vue Static Files
    # =========================
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # =========================
    # Backend & Auth (Dynamic Resolution)
    # =========================
    location ~ ^/(api|oauth2|login)/ {
        # Gunakan DNS internal Docker agar bisa resolve nama service
        resolver 127.0.0.11 valid=30s;

        # Variabel agar Nginx tidak crash jika gateway service sedang restart
        set $target_gateway fountation-gateway-service;
        proxy_pass http://$target_gateway:8080;

        # Increase timeouts for slow Raspberry Pi processing
        proxy_ignore_client_abort on;
        proxy_connect_timeout 300s;
        proxy_send_timeout    300s;
        proxy_read_timeout    300s; # This is the most important one
        keepalive_timeout     300s;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}